# This file is part of the BenGorUser package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

services:
    bengor_user.swift_mailer_bridge.infrastructure.mailing.swift_mailer_user_mailer:
        class: BenGorUser\SwiftMailerBridge\Infrastructure\Mailing\SwiftMailerUserMailer
        arguments:
            - '@swiftmailer.mailer.default'
        public: false

    bengor_user.mailer.swift_mailer:
        alias: bengor_user.swift_mailer_bridge.infrastructure.mailing.swift_mailer_user_mailer
